<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <PackageId>NotificationServices.Email.Abstractions</PackageId>
    <Version>1.0.0</Version>
    <Authors>Mohammad Amin Nazeri</Authors>
    <Description>Abstractions and models for reusable Email notification services in .NET applications.</Description>
    <PackageTags>dotnet;csharp;email;notification;otp;abstractions;dependency-injection</PackageTags>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/Mohammad-Amin-Nazeri/Notification_Services_Pattern</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\README.md" Pack="true" PackagePath="README.md" />
    <None Include="..\..\LICENSE" Pack="true" PackagePath="LICENSE" />
  </ItemGroup>

</Project>
